CREATE TABLE Radnik (
    MBR INTEGER PRIMARY KEY AUTOINCREMENT,
    IME TEXT NOT NULL,
    PRZ TEXT NOT NULL,
    PLT INTEGER NOT NULL,
    SEF INTEGER
);
CREATE TABLE Projekat (
    SPR INTEGER PRIMARY KEY AUTOINCREMENT,
    NAP TEXT NOT NULL,
    RUK INTEGER NOT NULL
);
CREATE TABLE Radproj (
    MBR INTEGER NOT NULL,
    SPR INTEGER NOT NULL,
    BRC INTEGER DEFAULT 0 NOT NULL,
    PRIMARY KEY(MBR, SPR)
);
CREATE TABLE Queries (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    QUERY TEXT NOT NULL,
    DATETIME TEXT NOT NULL,
    SUCCEEDED INTEGER DEFAULT 0 NOT NULL
);
CREATE TABLE Settings (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    REMINDER INTEGER DEFAULT 0 NOT NULL
);

INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Milan', 'Savic', 100000, NULL);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Sima', 'Rudic', 150000, NULL);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Sasa', 'Matic', 50000, 1);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Stefan', 'Rodic', 350000, 1);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Matija', 'Brdad', 250000, 2);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Nikola', 'Sinjicanin', 22000, 3);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Stefan', 'Sibdzija', 330000, NULL);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Nemanja', 'Lukic', 45000, 3);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Nebojsa', 'Kaskaj', 22000, 1);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Radivoje', 'Domanovic', 10000, 2);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Milan', 'Petric', 230000, 7);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Ratko', 'Nikolic', 30000, 7);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Bojan', 'Radivojevic', 90000, 7);
INSERT INTO Radnik(IME, PRZ, PLT, SEF) VALUES('Samir', 'Samardzija', 80000, 7);

INSERT INTO Projekat(NAP, RUK) VALUES('Kuvanje', 5);
INSERT INTO Projekat(NAP, RUK) VALUES('SQL Predavanje', 4);
INSERT INTO Projekat(NAP, RUK) VALUES('Web developing u flasku', 3);
INSERT INTO Projekat(NAP, RUK) VALUES('Django', 3);
INSERT INTO Projekat(NAP, RUK) VALUES('Statisticka matematika', 2);
INSERT INTO Projekat(NAP, RUK) VALUES('Sviranje', 6);
INSERT INTO Projekat(NAP, RUK) VALUES('Haskell', 7);
INSERT INTO Projekat(NAP, RUK) VALUES('Pevanje', 6);
INSERT INTO Projekat(NAP, RUK) VALUES('Game developing', 2);
INSERT INTO Projekat(NAP, RUK) VALUES('C++', 2);
INSERT INTO Projekat(NAP, RUK) VALUES('Pointeri u C-u', 2);

INSERT INTO Radproj(MBR, SPR, BRC) VALUES(1, 5, 10);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(2, 5, 2);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(4, 5, 5);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(5, 5, 15);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(1, 1, 20);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(1, 3, 32);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(1, 7, 23);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(7, 5, 50);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(7, 2, 44);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(8, 5, 32);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(4, 1, 321);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(4, 3, 67);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(4, 4, 91);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(4, 6, 5);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(3, 5, 99);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(3, 4, 50);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(3, 1, 44);
INSERT INTO Radproj(MBR, SPR, BRC) VALUES(5, 6, 23);

INSERT INTO Settings(REMINDER) VALUES(1);